name: haskell-programming-from-first-principles-solutions
version: 0.0.0
license: MIT

ghc-options: -Wall

dependencies:
 - base == 4.*

library:
  source-dirs: src

tests:
  spec:
    defaults: hspec/hspec@master
    dependencies: haskell-programming-from-first-principles-solutions
